[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.19.0",
    "background>=0.2.1",
    "flask>=3.1.0",
    "pymorphy2>=0.9.1",
    "requests>=2.32.3",
]
